-- GERADO a partir de sql/schema-terca-supabase-ajuste-10.sql (schema meme). NÃO edite à mão: se o ajuste 10 do
-- Terça mudar, regenere (ver scripts/gerar-sql-grupo.js) e cole este trecho nas instalações do Meme já existentes.
-- QUEM RODA: o usuário, no SQL Editor do Supabase, no projeto que já tem o schema "meme".
set search_path = meme;

-- Ajuste 10: pendências (dívida avulsa de um jogador, cobrada "no olho" no próximo check-in).
-- QUEM RODA: o usuário, no SQL Editor do Supabase. Pode ser executado mais de uma vez sem estragar nada.
--
-- Pendência NÃO mexe no caixa: é só um aviso que aparece no check-in (ver finPendenciasDe no front)
-- até um organizador/admin marcar como paga. Mesma forma de fin_lancamentos (nada é apagado; "baixar"
-- marca a linha, não remove).
create table if not exists fin_pendencias (
  id text primary key,
  jogador_id text references jogadores(id),
  jogador_nome text,
  valor numeric(10,2),
  observacao text,
  data date,
  criado_por text,
  criado_em timestamptz,
  status text not null default 'pendente' check (status in ('pendente','paga')),
  baixado_por text,
  baixado_em timestamptz,
  -- mesma ideia das outras tabelas do financeiro (ajuste 3): ordem de inserção dada pelo banco, nunca pelo código
  ordem bigint generated by default as identity
);
